// ============================================================
// AUTO — Pernyataan kode etik penggunaan AI generatif, data dari data.yaml
// ============================================================

#import "../template/lib.typ": *

#let en(body) = text(size: 8pt)[#body]

#let pernyataan-ai(data) = {
  headz[PERNYATAAN KODE ETIK \ PENGGUNAAN AI GENERATIF]
  v(-0.6cm)
  align(center)[#en[_Code of Conduct Statement: Generative AI or AI-Assisted Usage_]]

  set par(first-line-indent: 0pt)

  v(0.5cm)
  [Saya yang bertanda tangan di bawah ini: \ #v(-12pt)#en[_I, the undersigned:_]]
  v(0cm)

  entry-fields(row-gutter: 10pt, (
    (
      [Nama Mahasiswa / NRP \ #v(-12pt)#en[_Full Name / Student ID_]],
      [#data.mahasiswa.nama / #data.mahasiswa.nrp],
    ),
    (
      [Program Studi \ #v(-12pt)#en[_Study Program_]],
      [S-1 Teknik Informatika],
    ),
    (
      [Judul Tugas Akhir \ #v(-12pt)#en[_Final Project Title_]],
      {set par(leading: 0.8em); [#data.judul.id]},
    ),
  ))

  v(0cm)
  [dengan ini menyatakan bahwa pada Tugas Akhir dengan judul di atas tersebut: \
  #v(-12pt)#en[_hereby declare that in the Final Project with the above title:_]]
  v(0cm)

  block({
  set par(justify: true)
  table(
    columns: (1cm, 1fr, 1.2cm),
    align: (center, left, center),
    table.header(
      table.cell(align: center + horizon, fill: rgb("#D9D9D9"))[*No.*],
      table.cell(align: center + horizon, fill: rgb("#D9D9D9"))[*Pernyataan* \ #v(-12pt)#en[_Statement_]],
      table.cell(align: center + horizon, fill: rgb("#D9D9D9"))[*(✅)*],
    ),
    [1.],
    [Saya hanya menggunakan AI generatif sebagai alat bantu untuk memperbaiki tata bahasa. AI generatif tidak digunakan untuk membuat isi Tugas Akhir. \ #v(-12pt)#en[_I only used generative AI as a tool to improve the readability or language of the text in my Final Project. It was not used to generate a complete text of my work._]],
    [],
    [2.],
    [Saya telah memeriksa dan/atau memperbaiki seluruh bagian dari Tugas Akhir saya yang dibantu oleh AI generatif agar sesuai dengan baku mutu penulisan karya ilmiah. \ #v(-12pt)#en[_I have reviewed and refined all aspects of my work that generative AI assists with, ensuring it adheres to the standards of academic writing._]],
    [],
    [3.],
    [Saya tidak menggunakan AI generatif untuk pembuatan data primer, grafik dan/atau tabel pada Tugas Akhir saya. \ #v(-12pt)#en[_I did not use generative AI to generate primary data, figures, and/or tables in my work._]],
    [],
    [4.],
    [Saya telah memberikan atribusi/pengakuan terhadap alat AI yang digunakan, secara rinci pada suatu bagian pada lampiran. \ #v(-12pt)#en[_I have acknowledged the use of generative AI in any part of the work in the specific appendix page._]],
    [],
    [5.],
    [Saya memastikan tidak ada plagiarisme, termasuk hal yang berasal dari penggunaan AI generatif. \ #v(-12pt)#en[_I have ensured that there is no plagiarism issue in the work, including any parts generated by AI._]],
    [],
  )
  })

  v(0cm)
  align(right)[
    #box(width: 30%)[
      #align(center)[
        #data.institusi.kota, #data.tanggal #data.bulan.id #data.tahun \
        Mahasiswa
        #place(center, dy: -0.6cm)[
          #image("../assets/figures/ttd-shutterstock.png", height: 2cm)
        ]
        #v(1.2cm)

        #data.mahasiswa.nama \
        NRP. #data.mahasiswa.nrp
      ]
    ]
  ]
}
